// detector.js — runs in the MAIN world (page context)
// Reads the video category + other "is this a music video?" signals
// from YouTube's internal data and exposes them to the content script
// via data attributes on <html>.
//
//   data-yt-category   — lowercase category string from ytInitialPlayerResponse
//                        (e.g. "music", "education", "people & blogs")
//   data-yt-music      — "music" if any music signal fired, "no" otherwise
//                        (also set to "auto-generated" / "title" for debugging)
//
// Music signal sources (any one is enough):
//   1. ytInitialPlayerResponse.videoDetails.category === "Music"
//   2. <meta itemprop="genre"> equals "Music"
//   3. video title contains "music" or "song" (word-boundary, case-insensitive)
//   4. video is auto-generated (YouTube only auto-generates music videos)
//   5. channel/author has a verified-artist music badge (e.g. a "♫" symbol
//      next to the artist name in the owner/renderer JSON)

(function () {
  'use strict';

  function pickVideoDetails() {
    try {
      return window.ytInitialPlayerResponse?.videoDetails
          || window.ytInitialData?.contents?.twoColumnWatchNextResults?.results?.results?.contents?.[0]?.videoPrimaryInfoRenderer?.title?.runs?.[0]?.text
          ? { /* synthetic */ }
          : null;
    } catch { return null; }
  }

  function readMetaGenre() {
    const m = document.querySelector('meta[itemprop="genre"]');
    return m ? (m.getAttribute('content') || '').toLowerCase() : '';
  }

  function titleHasMusicKeyword(title) {
    if (!title) return false;
    const t = String(title).toLowerCase();
    // Word-boundary match against common music-video title markers.
    //   music, song, songs, musical
    //   official video, official music video, official audio, official lyric,
    //   lyric video, lyrics video, music video
    // The "official video" / "official audio" markers are YouTube's
    // standard convention for music content and strongly indicate this
    // is a music video even when the category is missing.
    return /\bmusic\b|\bsong\b|\bsongs\b|\bmusical\b|\b(music\s+video|lyric\s+video|lyrics\s+video|official\s+(video|music\s+video|audio|lyric|lyrics))\b/.test(t);
  }

  function isAutoGenerated() {
    // YouTube auto-generates Topic channels for almost every music artist.
    // The author URL for those channels is /channel/UC... and the channel
    // name starts with the artist name + " - Topic".
    try {
      const vd = window.ytInitialPlayerResponse?.videoDetails;
      if (!vd) return false;
      // videoDetails has no direct flag, but author is suffixed with " - Topic"
      const author = String(vd.author || '');
      if (/\s-\sTopic\s*$/.test(author)) return true;
      // Defensive: some player responses include isLiveContent or other
      // markers; we keep auto-generated detection narrowly scoped.
      return false;
    } catch { return false; }
  }

  function hasArtistMusicBadge() {
    // The verified-artist music badge appears as an icon (a small
    // musical-note SVG / image) next to the channel name. YouTube also
    // marks the JSON with a `badges` array on the channel renderer.
    try {
      // Path through ytInitialData for the long-byline / owner renderer
      const data = window.ytInitialData;
      if (!data) return false;
      const results = data?.contents?.twoColumnWatchNextResults?.results?.results?.contents || [];

      // Helper: search recursively for a badges array with an
      // "OFFICIAL_ARTIST_BADGE" metadataBadgeRenderer (YouTube's internal
      // identifier for the verified-music-artist icon).
      function hasArtistBadge(node) {
        if (!node || typeof node !== 'object') return false;
        if (Array.isArray(node)) {
          for (const item of node) if (hasArtistBadge(item)) return true;
          return false;
        }
        const badgeRenderer = node.metadataBadgeRenderer;
        if (badgeRenderer) {
          const style = String(badgeRenderer.style || '').toUpperCase();
          const id = String(badgeRenderer.icon?.iconType || '').toUpperCase();
          const tooltip = String(badgeRenderer.tooltip || '').toLowerCase();
          if (
            style.includes('OFFICIAL_ARTIST') ||
            style.includes('MUSIC') ||
            id === 'OFFICIAL_ARTIST_BADGE' ||
            id.includes('MUSIC') ||
            tooltip.includes('official artist') ||
            tooltip.includes('music')
          ) {
            return true;
          }
        }
        for (const k of Object.keys(node)) {
          if (hasArtistBadge(node[k])) return true;
        }
        return false;
      }
      return hasArtistBadge(results);
    } catch { return false; }
  }

  function detect() {
    let category = '';
    let title = '';
    try {
      const vd = window.ytInitialPlayerResponse?.videoDetails || {};
      category = String(vd.category || '').toLowerCase();
      title = String(vd.title || '');
    } catch { /* ignore */ }

    const metaGenre = readMetaGenre();
    const titleHit = titleHasMusicKeyword(title);
    const autoGen = isAutoGenerated();
    const artistBadge = hasArtistMusicBadge();

    const isMusic = (
      category === 'music' ||
      metaGenre === 'music' ||
      titleHit ||
      autoGen ||
      artistBadge
    );

    let reason = 'no';
    if (category === 'music') reason = 'category';
    else if (metaGenre === 'music') reason = 'meta-genre';
    else if (autoGen) reason = 'auto-generated';
    else if (artistBadge) reason = 'artist-badge';
    else if (titleHit) reason = 'title';

    document.documentElement.setAttribute('data-yt-category', category);
    document.documentElement.setAttribute('data-yt-music', isMusic ? 'yes' : 'no');
    document.documentElement.setAttribute('data-yt-music-reason', reason);
  }

  // YouTube SPA navigation events
  document.addEventListener('yt-navigate-finish', () => setTimeout(detect, 300));
  document.addEventListener('yt-page-data-updated', detect);

  // Initial page load
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', detect);
  } else {
    detect();
  }
})();